asfadmin/thin-egress-app

README.MD
cloudformation/thin-egress-app.yaml

Putting values in quotes in UseReverseBucketMap allows the deployment
via command line

PR-1856 Removed allowedpattern from URSAuthCredsSecretName

---

build/Jenkinsfile
build/download_test.sh
lambda/common/common.py

[PR-1970] Fix retrieve_secret() error handling. Fix template pathing.

 [PR-1937] Added automated testing

---

build/Jenkinsfile

https://github.com/aws/aws-cli/issues/2599
we can remove these lines later.

Temp Fix to overcome bug in awscli

---

NGAP-DEPLOY-README.MD

This is one of three related documentation PRs.  The other two are:
* https://github.com/nasa/cumulus/pull/1071
* https://github.com/nasa/cumulus-template-deploy/pull/18

CUMULUS-1321 Update NGAP docs to use Terraform

---

build/Jenkinsfile

And when doing the replace, swap in an actual bucket name.

Only replace code bucket when we're not building tea

---

build/Jenkinsfile
build/dependency_builder.sh
build/dependency_layer_builder.Dockerfile
build/download_test.sh
cloudformation/thin-egress-app.yaml
lambda/app.py
lambda/requirements.txt
terraform/main.tf
terraform/variables.tf

This should not be merged before https://github.com/asfadmin/rain-api-core/pull/8

In-region download role and JWT

---

lambda/app.py
lambda/templates/root.html

Resolves https://github.com/asfadmin/thin-egress-app/issues/85 and https://github.com/asfadmin/thin-egress-app/issues/84

NGAP/Cloudfront Integration changed to mask STAGE

---

cloudformation/thin-egress-app.yaml
terraform/main.tf
terraform/variables.tf

Plus adding SSL domain_cert_arn to terraform module

[PR-2196] Remove ASF-centric default CloudFormation param options

---

lambda/app.py

Reverts asfadmin/thin-egress-app#108

Revert "Updated if statement to check for 'usr-user-id'"

---

terraform/main.tf

Hotfix for creating build-stamped lambda zips for Terraform

Fix lambda updates

---

cloudformation/thin-egress-app.yaml

Set output of `ExternalEndpoint` and `URSredirectURI` appropriately based on `DomainNameIsSet` condition

[ISSUE#125] remove extraneous URSredirectNoDomainURI field

---

NGAP-DEPLOY-README.MD
README.MD
build/Jenkinsfile
setup_jwt_cookie.sh
terraform/main.tf
terraform/variables.tf

Makes terraform a little more discrete

Refactor terraform to push CF template into aws_s3_bucket.lambda_source bucket

---

lambda/app.py

Send Cache-Control header indicating presigned URL expiration

---

build/dependency_builder.sh
build/download_test.sh
cloudformation/thin-egress-app.yaml
lambda/app.py
lambda/requirements.txt

Reverts asfadmin/thin-egress-app#171
Stray tap caused this

Revert "Cumulus 1959"

---

build/dependency_builder.sh
build/download_test.sh
cloudformation/thin-egress-app.yaml
lambda/app.py
lambda/requirements.txt

This PR  adds '/locate' endpoint, updates cloudformation/stack to provide it. 
In progress, integration tests are needed, but are dependent on non-public test artifacts

Add '/locate' endpoint 

---

.gitignore
README.MD
lambda/app.py
lambda/requirements.txt

Also handling cases where user doesn't sign the EULA

Token sharing implemented

---

lambda/app.py

also improved error handling in get_user_from_token()

PR-2487 different handling for bearer and other types of auth

---

cloudformation/thin-egress-app.yaml

We need a long term fix for this.

Remove Session max during value... This is breaking NGAP.

---

build/Jenkinsfile
lambda/app.py

Also minor adjustments to jenkinsfile
closes #258

Git submodule that supports new logging features

---

lambda/requirements.txt

Email address included in jwt payload

---

lambda/app.py
lambda/templates/base.html

Request ID in user-facing error page

---

cloudformation/thin-egress-app.yaml
lambda/app.py

Pubkey endpoint

---

build/test/download_test.py

Checks to make sure env vars were set in download_test.py

---

build/Jenkinsfile
cloudformation/thin-egress-app.yaml
lambda/tea_bumper.py

Also updated the rain-api-core

Creation of TEAbumper lambda #328

---

cloudformation/thin-egress-app.yaml

Add EC2:* permissions required for creating lambdas inside VPC

---

build/test/download_test.py
lambda/app.py

Reverts asfadmin/thin-egress-app#373

Revert "Allow bearer token validation for accessing restricted data"

---

build/test/download_test.py
lambda/app.py

Reverts asfadmin/thin-egress-app#375

Revert "Revert "Allow bearer token validation for accessing restricted data""

---

lambda/app.py

And lots of whitespace got removed, apparently. Also reordered imports

#421 removed log.debug(download)

---

.github/workflows/lint.yml
.github/workflows/test.yml
README.MD
build/test/download_test.py
codecov.yml
lambda/app.py
lambda/tea_bumper.py
lambda/update_lambda.py
setup.cfg
tests/test_dummy.py

isort and flake8 can (and should) be configured using a `setup.cfg`. Still need to see about a coverage reporting tool.
Once we get this working how we like we can refactor to a reusable workflow.

Add GitHub Actions for lints and tests

---

tests_e2e/test_protected.py
tests_e2e/test_public.py

Adding tests for some things as I notice they're missing.

Additional end-to-end tests

---

.github/workflows/re-build.yml

The default keys for code and dependency zips were swapped

Fix default s3 keys

---

lambda/app.py
requirements.txt
tests/conftest.py
tests/test_app.py
tests_e2e/test_public.py

Applies the bucket map refactor from rain api core: https://github.com/asfadmin/rain-api-core/pull/195
Also refactors some of the timing code.
Fixes #417

Refactor bucket map checking

---

.github/workflows/deploy-docs-website.yml
docs/deploying.md
docs/technical.md
requirements/requirements-docs.txt

Fix mkdocs links

---

Makefile

Fix makefile for jenkins

---

.github/workflows/test.yml
Makefile
lambda/app.py
lambda/templates/base.html
lambda/templates/profile.html
lambda/templates/root.html
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt
tests/test_app.py

Integrate changes from https://github.com/asfadmin/rain-api-core/pull/229

PR-3151 Integrate template refactor changes

---

Makefile
lambda/app.py
tests/test_app.py

Chalice has support for middleware so we don't need to do the hack with subclassing

Refactor tea middleware

---

.pyup.yml

This should reduce the PR spam

Update pyup settings

---

cloudformation/thin-egress-app.yaml

This allows the AWS SNS for updated ips to trigger the lambda

PR-3496 add lambda permissions to SNS to invoke

---

.github/workflows/re-test-e2e.yml
Makefile
Makefile.config.example
cloudformation/thin-egress-app.yaml
docs/configuration.md
docs/deploying.md
docs/s3access.md
lambda/app.py
mkdocs.yml
requirements/requirements-dev.txt
requirements/requirements-test.txt
requirements/requirements.in
requirements/requirements.txt
terraform/main.tf
terraform/variables.tf
tests/test_app.py
tests_e2e/test_s3credentials.py

Replacement for #642 but with correct base branch...

PR-3244 Add s3 credentials endpoint

---

cloudformation/thin-egress-app.yaml.j2

Not sure how this got missed because I swear I tested it before...

Replace all references to api deployment

---

.github/workflows/deploy-docs-website.yml
.github/workflows/lint.yml
.github/workflows/re-build.yml
.github/workflows/re-status.yml
.github/workflows/re-test-e2e.yml
.github/workflows/release.yml
.github/workflows/test-e2e.yml
.github/workflows/test.yml

Seeing a bunch of warnings about deprecated stuff in the actions tab.

Fix GitHub actions deprecations

---

cloudformation/thin-egress-app.yaml.j2
docs/configuration.md
lambda/app.py
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt
tests/test_app.py

Update dependencies and add a (hopefully) nice error message when the bucket map validation fails.

PR-3244 Policy permission fix and dependency update

---

requirements/requirements-dev.txt
requirements/requirements.txt

Fixing CVE ReDoS 

---

lambda/app.py
tests/test_app.py

Fixes https://github.com/asfadmin/thin-egress-app/issues/474

Specify correct Content-Type for /profile

---

requirements/requirements-dev.txt
requirements/requirements-docs.txt
requirements/requirements-make.txt
requirements/requirements-test.txt
requirements/requirements.txt

Closes #693 
Closes #692 
Closes #667 
Closes #666
Inquirer is pinned by chalice which has not received an update since September of last year. There are some open issues on the chalice repo questioning if it is still receiving support. https://github.com/aws/chalice

PR-3844 Update dependencies

---

.github/workflows/lint.yml
.github/workflows/re-status.yml
.github/workflows/re-test-e2e.yml
.github/workflows/release.yml
.github/workflows/test-e2e.yml

Github has added some features to actions since these workflows were created that make a lot of things quite a bit simpler or nicer. In this PR I'm updating the workflows to make use of these new features.
1. Repository configuration variables. *Previously only secrets were available which caused a number of headaches since they are redacted in logs and the `secrets` context is restricted in where it can be used in the workflows.*
2. Inherit secrets when calling a reusable workflow. *Previously all secrets had to be listed explicitly which created some annoyingly long copy/pasta secret lists.*

Refactor GitHub Actions

---

setup.cfg
tea-cli/tea_cli/commands/quick_deploy.py
thin_egress_app/app.py

Update isort config

---

requirements/requirements-dev.txt
requirements/requirements-docs.txt
requirements/requirements-make.txt
requirements/requirements-test.txt
requirements/requirements.txt
tests/conftest.py

Closes #781 
Closes #782 
Closes #793 
Closes #795 
Closes #796

PR-5727 Update dependencies

---

.github/workflows/test-e2e.yml

I want to be able to test that the e2e tests will pass before merging

Add workflow_dispatch trigger to e2e tests workflow

---

requirements/requirements-dev.txt
requirements/requirements-docs.txt
requirements/requirements-make.txt
requirements/requirements-test.txt
requirements/requirements.txt

I have:
- Resources and Data Structures are sorted by ABC or a defined sorting pattern

PR-6820: Update requirements
