- cloudformation/thin-egress-app.yaml
- terraform/outputs.tf
Adding two additional outputs to the CF stack which are needed to support integrating the S3 credentials endpoint.
> Add REST API outputs to support Terraform

- terraform/main.tf
- terraform/outputs.tf
This PR fixes a failure that occurs when `var.log_api_gateway_to_cloudwatch` is enabled on an existing TEA deployment. Due to the way Terraform fetches outputs, it will fail saying that the `ApiGatewayLogGroupEgress` output does not exist, which is because it attempts to fetch the output in a phase before applying the change that will actually create the output in Cloudformation, which is triggered off the same var.
By using a data resource that depends on the Cloudformation resource, we can delay evaluation of the output until after the update has been applied, resolving the above issue.
> fetch CF output after update by depending

- cloudformation/thin-egress-app.yaml
Only create ExtDomainName if a domain is set, and the app is NOT in NGAP. 
creating `AWS::ApiGateway::DomainName` forces an APIGateway to EdgeOptimized instead of PRIVATE.
> NGAP2 Compatibility

- build/Jenkinsfile
- terraform/main.tf
v47 of TEA is failing to deploy in Terraform. The TEA lambda code is stored in `lambda.zip`, which is included in the TF module's zip file. Some time recently, a `dependencylayer` zip was added as well. That file is not being included in the TF zip file, so TF deployments are failing in v47. This PR should fix that.
> Store dependencylayer in Terraform zip

- README.MD
- setup_jwt_cookie.sh
Because every developer will be setting up JWT Cookie secrets it would be nice if it can happen automatically, hence this PR.
> Automate setting up JWT secrets

- build/Jenkinsfile
- lambda/app.py
Reported versions will be `teatest-build.105` instead of `build.105` or `tea-build.58` instead of  `build.58`
> Buildstamp with $BUILDTAG instead of $NEWTAG

- cloudformation/thin-egress-app.yaml
This fails on established stacks
> Remove UpdateLambda Log Group

- terraform/outputs.tf
This is needed as the api_endpoint output provides the external facing
endpoint, however we don't always want internal/deployment queries to hit cloudfront/external access solutions
> Updates TEA outputs to provide consistent internal API reference

- build/test/download_test.py
This requires functionality NOT in production EDL.
> Add a semi-function test for bearer token support

- terraform/outputs.tf
When trying to upgrade from TEA build 88 to TEA build 100+ for a Cumulus deployment, Cumulus users (myself included) are getting this error:
```
Error: Missing map element
on .terraform/modules/thin_egress_app/outputs.tf line 25, in output "egress_lambda_name":
25:   value = aws_cloudformation_stack.thin_egress_app.outputs.EgressLambdaName
|----------------
| aws_cloudformation_stack.thin_egress_app.outputs is map of string with 5 elements
This map does not have an element with the key "EgressLambdaName".
```
See ticket CUMULUS-2258 for other impacted users.
After investigating the issue, it is caused by the fact that the [Terraform code refers to an output from Cloudformation stack named `EgressLambdaName`](https://github.com/asfadmin/thin-egress-app/blob/devel/terraform/outputs.tf#L25), …
> use TF lookup() function to conditionally add egress_lambda_name output

- build/deploy.sh
Without `--force-delete-without-recovery`, the secrets are left in a `marked for delete` purgatory where they cannot be updated but don't show up in the AWS console.
> More powerful secret destruction

- build/test/download_test.py
- lambda/app.py
Fix [issue 137](https://github.com/asfadmin/rain-api-core/issues/137)
> Allow bearer token validation for accessing restricted data

- lambda/update_lambda.py
This change came about because the "DownloadRoleInRegion" lambda update was failing to properly update, complaining that the role size was too big.
We were deploying in us-east-1, so the CIDR range fetched was about 799 addresses.
With cidr_merge it got it down to about 449, or saving about 6000 bytes on the role.
This should allow the role policy document to be adequately created for now. It will also dynamically adjust as AWS changes their IP list.
Resubmitting because it was supposed to branch off devel and not master.
> Update TEA Lambda to attempt to reduce CIDR range

- requirements.txt
Might be a good idea to pin dependency versions with `pip-tools` or `pipenv`. These tools will automatically pin the entire dependency tree in order to produce deterministic builds. They also both provide a single command upgrade mechanism to pin everything to the latest version.
> PR-3041 Update dependencies

- scripts/sed.py
The template description was not being replaced because `^` was only matching the beginning of the file.
> Compile pattern in multiline mode

- Makefile
- Makefile.config.example
- README.MD
- build/Jenkinsfile
Some changes I needed to do to be able to build TEA with a local development version of rain api core.
> Improve support for building local dependencies

- .github/workflows/re-test-e2e.yml
- tests_e2e/test_gdal.py
- tests_e2e/test_public.py
It came up in a discussion about refactoring the HEAD route that there may be some use cases where the HEAD operation needs to be publicly accessible and that there had been some issues with certain GDAL functions in the past when the HEAD route wasn't working correctly.
I took an example from https://github.com/isce-framework/isce2/discussions/349 and converted it into an end to end test.
> Add end-to-end tests for GDAL operations

- .github/workflows/re-test-e2e.yml
- .github/workflows/release.yml
- .github/workflows/test-e2e.yml
- tests_e2e/conftest.py
The artifact names were based on branch name, so when the end to end tests would run against the devel branch, sometimes the lambda code would not be forced to update since the file name was the same. This should ensure that a new file is created for each run, and therefore the lambda code is always refreshed.
> Fix end to end tests deploy

- .github/workflows/re-test-e2e.yml
- build/Jenkinsfile
It seems that one test in particular `tests_e2e/test_jwt_blacklist.py::test_validate_valid_jwt` sometimes fails due to the lambda timeout since it always triggers a cold start. I'm not sure there's much we can do about that besides increase the timeout.
> Increase lambda timeout for end to end tests

- cloudformation/thin-egress-app.yaml
The tea bumper needs the dependency layer so it can import from rain api core
> PR-3204 Add dependency layer to tea bumper

- cloudformation/thin-egress-app.yaml
This allows the AWS SNS for updated ips to trigger the lambda
> PR-3496 feat: add lambda permissions to SNS to invoke

- Makefile
- Makefile.config.example
- cloudformation/thin-egress-app.yaml
- docs/configuration.md
- docs/deploying.md
- docs/s3access.md
- lambda/app.py
- mkdocs.yml
- requirements/requirements-dev.txt
- requirements/requirements-test.txt
- requirements/requirements.in
- requirements/requirements.txt
- terraform/main.tf
- terraform/variables.tf
- tests/test_app.py
- tests_e2e/test_s3credentials.py
Adds and endpoint to dispense temporary s3 credentials like the cumulus-distribution module does. One key difference is that I'm calling STS directly from TEA whereas cumulus-distribution goes through the NGAP provided `gsfc-ngap-sh-s3-sts-get-keys` lambda function. I'm not sure why cumulus-distribution uses that lambda, but if we can get away with not calling it then I think that's much preferred as it make the code simpler and probably faster too. Either way we have to support calling sts directly so that TEA can still function outside of NGAP.
TODO:
> PR-3244 Add s3 credentials endpoint

- lambda/app.py
- requirements/requirements.in
- requirements/requirements.txt
- tests/test_app.py
The main fix comes from updating the rain-api-core dependency to the version that will dedupe statement resources
> PR-3244 S3 credential fix

- .github/workflows/re-test-e2e.yml
The build breaks on ubuntu 22 because a newer version of gdal is installed which doesn't match the pinned version installed by pip.
> Pin ubuntu version in e2e github workflow

- lambda/app.py
- tests/test_app.py
- tests_e2e/conftest.py
- tests_e2e/test_protected.py
- tests_e2e/test_public.py
When accessing public data the `A-userid` field in the presigned URL which is used for metrics purposes would be set to `None` even if the user was logged in.
> Fix userid none for public data

- .github/workflows/deploy-docs-website.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
- README.MD
- docs/technical.md
This should accompany a repo settings change to use `devel` for the default branch. This would make our development workflow a lot less annoying as the default base branch when opening a PR would be the correct branch most of the time.
> PR-4048 use devel as default branch

- thin_egress_app/app.py
There's a cloudformation parameter for it which sets an environment variable, but we're never reading the variable. Probably this got dropped when we refactored the JWT code.
> Get session ttl from environment variable

- requirements/requirements-dev.txt
- requirements/requirements-docs.txt
- requirements/requirements-make.txt
- requirements/requirements-test.txt
- requirements/requirements.txt
The mkdocs ASF theme was updated in https://github.com/ASFHyP3/mkdocs-asf-theme/issues/27 to support the latest version of mkdocs material, so this should address the warnings about the outdated version of mkdocs material.
> PR-5371 Update all dependencies

- requirements/requirements.in
- requirements/requirements.txt
- tests/data/old_style_bucket_map_example.yaml
- tests/test_app.py
- thin_egress_app/app.py
The `/locate` endpoint seems to be the last place that had special handling code to interact with the bucket map that was not going through the `BucketMap` class. This change will ensure that the bucket map behavior is consistent for `/locate` and other functionality. Specifically, this allows the old-style bucket maps with no top level `MAP` key to work with `/locate` (previously a 500 error would be returned).
> PR-5069 Refactor locate endpoint

- .github/workflows/re-test-e2e.yml
- tests_e2e/test_protected.py
#777 introduced a change to how the locate endpoint works with respect to the `BucketnamePrefix` parameter. Previously the `bucket` parameter expected the name of the bucket WITHOUT the prefix. This is arguably not the desired behavior as it requires the caller of the application to know which part of the bucket name is the prefix and to be able to strip it out in the request. However, this does create a breaking change in the API so we have a few options:
1. Bump the version number to 2.x to reflect the fact that this is a breaking change.
2. Decide that the old behavior was a bug and therefore we only bump the bugfix number 1.3.x. *This is probably not the best option because it's possible that there are some TEA deployments out there that might be affected by this*.
3. Support both for …
> Fix locate endpoint bucket name test

- tests/test_app.py
- tests_e2e/test_cors.py
- thin_egress_app/app.py
Some libraries will automatically make this `OPTIONS` request and we need to respond with the appropriate headers to prevent cross origin requests from being blocked.
> PR-5790 Add CORS preflight OPTIONS request

- .gitignore
- Makefile.config.example
- README.MD
- requirements/requirements.in
- requirements/requirements.txt
- tests/test_app.py
- thin_egress_app/app.py
When the A-api-request-uuid query parameter is included in the request, it will be added to the s3 presigned url so that it can be extracted as a metric when downloaded.
> Add support for A-api-request-uuid query parameter

- terraform/main.tf
- terraform/variables.tf
Adds the DAR=YES tag to the s3 bucket created by the terraform module for storing the build artifacts.
> PR-5848 Add DAR tag to terraform module

- tea-cli/pyproject.toml
- tea-cli/tea_cli/main.py
Adds help descriptions to the subcommands
> Improve tea-cli help text

- .gitignore
- terraform/main.tf
- terraform/providers.tf
> Use aws_s3_object instead of aws_s3_bucket_object

- terraform/main.tf
While doing Cumulus upgrades, I noticed that on every update Terraform was adding something like this to the plan:
```
~ resource "aws_s3_bucket_object" "lambda_code_dependency_archive" {
~ etag                          = "661d0e0eb0bc955857a7a71087a4208a-2" -> "96bac3b47b39d00107729959bc6689d3"
id                            = "96bac3b47b39d00107729959bc6689d3.zip"
tags                          = {}
+ version_id                    = (known after apply)
}
```
The [etag](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_object#etag) attribute has a warning about using it for files larger than 16MB as it can cause this behavior where the etag after uploading with a multipart upload does not match the full source code hash causing Terraform to needlessly update …
> Fix Terraform updating dependency layer object when content hasn't changed

- requirements/requirements.in
- requirements/requirements.txt
- tests/__init__.py
- tests/test_app.py
- thin_egress_app/app.py
Using code from: https://github.com/asfadmin/rain-api-core/pull/296
> Refactor EDL call to use EdlClient from rain-api-core

- requirements/requirements.in
- requirements/requirements.txt
- tests/conftest.py
- tests/test_app.py
- thin_egress_app/app.py
Replaces the old bearer token logic with updated handling for JWT bearer tokens. The user_id is extracted from the bearer token directly, eliminating 1 call to EDL, and then the token is used to fetch the user profile, simultaneously verifying the validity of the token and returning the profile information. That eliminates another EDL call for fetching an application bearer token.
TODO: 
- https://github.com/asfadmin/rain-api-core/pull/297
> PR-3242 Improve handling of JWT bearer tokens

- tests/test_app.py
- thin_egress_app/app.py
Currently if we send an auth header without the string `Bearer` we'll see an error like this:
```
$ curl -X GET --header "Authorization: foobar" http://...
{"Code":"InternalServerError","Message":"An internal server error occurred."}
```
With these changes:
```
$ curl -X GET --header "Authorization: foobar" http://...
{"status_code":400,"error_description":"Malformed Authorization header"}
```
NOTE: CMR accepts an authorization header containing just the token, so it is reasonable that some users might see that and try the same approach with TEA.
> Add error handling for malformed auth headers
